CREATE TABLE IF NOT EXISTS nba.other_stats (
  game_id bigint NOT NULL,
  league_id bigint,
  team_id_home bigint,
  team_abbreviation_home text,
  team_city_home text,
  pts_paint_home bigint,
  pts_2nd_chance_home bigint,
  pts_fb_home bigint,
  largest_lead_home bigint,
  lead_changes bigint,
  times_tied bigint,
  team_turnovers_home bigint,
  total_turnovers_home bigint,
  team_rebounds_home bigint,
  pts_off_to_home bigint,
  team_id_away bigint,
  team_abbreviation_away text,
  team_city_away text,
  pts_paint_away bigint,
  pts_2nd_chance_away bigint,
  pts_fb_away bigint,
  largest_lead_away bigint,
  team_turnovers_away bigint,
  total_turnovers_away bigint,
  team_rebounds_away bigint,
  pts_off_to_away bigint,
  PRIMARY KEY (game_id)
);

